# Generated by Django 5.2 on 2026-07-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='الباركود')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='الشركة المصنعة')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='المورد')),
            ],
        ),
    ]
