# Generated by Django 5.2 on 2026-07-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='الباركود')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='الشركة المصنعة')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('minimum_stock', models.PositiveIntegerField(default=5, verbose_name='الحد الأدنى للمخزون')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنتاج')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('available', 'متوفر'), ('unavailable', 'غير متوفر')], default='available', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='categories.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
                'ordering': ['name'],
            },
        ),
    ]
