# Generated by Django 5.2 on 2026-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشكل الدوائي'),
        ),
    ]
