# Generated by Django 5.2 on 2026-08-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_dosage_form'),
        ('product_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='product_types.producttype', verbose_name='نوع المنتج'),
        ),
    ]
