# Generated by Django 5.2 on 2026-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المادة الفعالة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'مادة فعالة',
                'verbose_name_plural': 'المواد الفعالة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_ingredients',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='medicines.activeingredient', verbose_name='المواد الفعالة'),
        ),
    ]
