# Generated by Django 5.2 on 2026-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('pharmacist', 'صيدلي')], default='pharmacist', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['full_name'],
            },
        ),
    ]
