# Generated by Django 5.2 on 2026-08-22 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_status_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='مدير الصيدلية', max_length=100, verbose_name='المسمى الوظيفي')),
                ('employee_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم الوظيفي')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الملف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مدير',
                'verbose_name_plural': 'ملفات المديرين',
                'ordering': ['id'],
            },
        ),
    ]
